version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: "yes"
       MYSQL_DATABASE: fever
       MYSQL_USER: fever
       MYSQL_PASSWORD: $MYSQL_PASSWORD
     ports:
       - "3306:3306"
   amq:
     image: rabbitmq:3-management
     volumes:
       - queue_data:/var/lib/rabbitmq
     restart: always
     environment:
       RABBITMQ_DEFAULT_USER: fever
       RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
       RABBITMQ_DEFAULT_VHOST: "/"
     ports:
       - "15672:15672"
       - "5672:5672"

volumes:
    db_data:
    queue_data:


