version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: "yes"
       MYSQL_DATABASE: fever
       MYSQL_USER: fever
       MYSQL_PASSWORD: $MYSQL_PASSWORD

   amq:
     image: rabbitmq:3-management
     volumes:
       - queue_data:/var/lib/rabbitmq
     restart: always
     hostname: amq
     environment:
       RABBITMQ_DEFAULT_USER: fever
       RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
       RABBITMQ_DEFAULT_VHOST: "/"
     ports:
       - "15672:15672"
   web:
     depends_on:
       - db
       - amq
     image: sheffieldnlp/fever-interface:latest
     ports:
       - "80:8080"
     restart: always
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost/ping"]
       interval: 15s
       timeout: 10s
       retries: 3
     environment:
       HIBERNATE_URL: jdbc:mysql://db/fever?characterEncoding=utf-8
       HIBERNATE_USERNAME: fever
       HIBERNATE_PASSWORD: $MYSQL_PASSWORD

       CATALINA_OPTS: "-Dauth.url=$AUTH_URL -Dhibernate.url=jdbc:mysql://db/fever?characterEncoding=utf-8 -Dhibernate.username=fever -Dhibernate.password=$MYSQL_PASSWORD -Dmessaging.username=fever -Dmessaging.password=$RABBITMQ_PASSWORD -Dmessaging.host=amq -Drecaptcha.key=$RECAPTCHA_KEY -Dauth.smtp.username=$SMTP_USERNAME -Dauth.smtp.password=$SMTP_PASSWORD -Dauth.smtp.from=$SMTP_FROM"

volumes:
    db_data:
    queue_data:


